ARG QGIS_VERSION=3.40
FROM sourcepole/qwc-qgis-server:$QGIS_VERSION

USER root

# MSSQL drivers
# https://docs.microsoft.com/de-de/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15

RUN \
    curl -sSL -O https://packages.microsoft.com/config/ubuntu/$(grep VERSION_ID /etc/os-release | cut -d '"' -f 2)/packages-microsoft-prod.deb && \
    dpkg -i packages-microsoft-prod.deb && \
    rm packages-microsoft-prod.deb && \
    apt-get update && \
    ACCEPT_EULA=Y apt-get install -y msodbcsql18 libqt5sql5-odbc && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ARG UID=33
USER $UID
